import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Header from "./header";
import Footer from "./footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Header/>
        <main className=" bg-slate-400 grid grid-cols-1">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
